language: python
env:
  matrix:
    - CI_TARGET=neovim
    - CI_TARGET=vim
before_install:
  - if [[ $CI_TARGET = neovim ]]; then pip install neovim; fi
install:
  - python setup.py -q install
before_script:
  - if [[ $CI_TARGET == neovim ]]; then eval "$(curl -Ss https://raw.githubusercontent.com/fwalch/bot-ci/nightly-test/scripts/travis-setup.sh) nightly-x64"; fi
  - if [[ $CI_TARGET == vim ]]; then sudo apt-get install vim-gnome; fi
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - if [[ $CI_TARGET == neovim ]]; then vroom --crawl --neovim ./examples/; fi
  - if [[ $CI_TARGET == vim ]]; then vroom --crawl ./examples/; fi
